import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-bright": "#f8fafb",
        "on-secondary-fixed": "#2a161b",
        "on-secondary-fixed-variant": "#5a4046",
        surface: "#f8fafb",
        "on-primary-container": "#3f5f56",
        secondary: "#73575d",
        "on-secondary-container": "#795d63",
        "on-tertiary-container": "#68572d",
        "primary-container": "#b5d8cc",
        "surface-container-highest": "#e1e3e4",
        "on-surface-variant": "#414845",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#f9e0aa",
        primary: "#45655b",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-variant": "#e1e3e4",
        tertiary: "#6e5c31",
        "on-surface": "#191c1d",
        "surface-tint": "#45655b",
        "secondary-fixed": "#ffd9e0",
        "inverse-on-surface": "#eff1f2",
        "surface-dim": "#d8dadb",
        "inverse-surface": "#2e3132",
        error: "#ba1a1a",
        "outline-variant": "#c1c8c4",
        "secondary-fixed-dim": "#e1bdc4",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#abcec2",
        "tertiary-fixed-dim": "#dcc490",
        "tertiary-container": "#e6ce99",
        background: "#f8fafb",
        "secondary-container": "#ffd9e0",
        "primary-fixed": "#c7eade",
        "on-background": "#191c1d",
        "surface-container-high": "#e6e8e9",
        "on-tertiary-fixed": "#251a00",
        "on-secondary": "#ffffff",
        outline: "#717975",
        "surface-container-low": "#f2f4f5",
        "surface-container": "#eceeef",
        "on-primary-fixed": "#002019",
        "on-primary-fixed-variant": "#2d4d44",
        "inverse-primary": "#abcec2",
        "on-tertiary-fixed-variant": "#55451c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        base: "8px",
        md: "24px",
        gutter: "20px",
        margin: "24px",
        lg: "48px",
        xl: "80px",
      },
      fontFamily: {
        epilogue: ["Epilogue", "sans-serif"],
        jakarta: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", fontWeight: "500" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-lg": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.04em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
